defmodule Crew.Worker.ToolStep do
  defstruct [:name, :before, :after]

  @schema [
    name: [type: :atom, required: true, doc: "A name of the tool"],
    before: [
      type: {:fun, 1},
      doc: "pre processing step before the tool is executed. Typically, this runs on the parameters received in the tool. "
    ],
    after: [
      type: {:fun, 1},
      doc: "post processing step after the tool is executed. Typically, this runs on the output generated by the tool. "
    ]
  ]

  def schema, do: @schema

  def transform(step) do
    "toolstep tranform was called" |> IO.inspect(label: "#{Path.relative_to_cwd(__ENV__.file)}:#{__ENV__.line}")
    {:ok, step}
  end
end
